In [62]:
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MultiLabelBinarizer
import ast
import pandas as pd
import numpy as np

after watching part of the sci kit learn crash course, i realized that i need to do some data processing in order for my ml algos to work. in this case, i need to clean up how my features are represented, and use one hot encoding for the majority of the categorical variables. i also need to scale my values.

In [63]:
data_raw = pd.read_csv("data/ranges.csv")
scaler = StandardScaler() # decided that standard scaler should be ok for this data set.
numeric_collumns = ["width_inches", "height_inches", "depth_inches", "burners", "price", "rating"]
data_raw_scalable_values = data_raw[numeric_collumns]
data_raw_scaled_values = scaler.fit_transform(data_raw_scalable_values)
numeric_data_scaled = pd.DataFrame(data_raw_scaled_values, columns=numeric_collumns)

In [64]:
#features will be done themselves, as each row is a array. will be using multi label binarizer from sci kit learn for this.

data_raw["features"] = data_raw["features"].apply(ast.literal_eval) # made the mistake of storing the features as a string instead of a list, easier to do this rather than remake the data set.

mlb = MultiLabelBinarizer()

features_encoded = mlb.fit_transform(data_raw["features"])

features_df = pd.DataFrame(
    features_encoded,
    columns=mlb.classes_,
    index=data_raw.index
)

In [65]:

encoder_collumns = ["brand", "category", "range_type", "finish"]
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)

encoded_values = encoder.fit_transform(data_raw[encoder_collumns]) #learns what features exist
encoded_names = encoder.get_feature_names_out(encoder_collumns) #gets the feature names out
encoded_df = pd.DataFrame(encoded_values, columns=encoded_names)
encoded_df

,brand_Bosch,brand_Cafe,brand_Fisher & Paykel,brand_Frigidaire,brand_GE,brand_KitchenAid,brand_LG,brand_Miele,brand_Monogram,brand_Samsung,...,brand_Wolf,category_range,range_type_dual fuel,range_type_electric,range_type_gas,range_type_induction,finish_Black,finish_Black Stainless,finish_Stainless Steel,finish_White
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
24996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
24997,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
24998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
24999,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [66]:
# brand tier encoding

encoder = OrdinalEncoder(categories=[['budget', 'mainstream', 'premium', 'luxury']])
data_raw["brand_tier"] = encoder.fit_transform(data_raw[["brand_tier"]])
data_raw[["brand_tier"]]

       brand_tier
0             2.0
1             2.0
2             2.0
3             1.0
4             3.0
...           ...
24995         1.0
24996         0.0
24997         1.0
24998         3.0
24999         1.0

[25000 rows x 1 columns]